### ISSUE TITLE
Componentes Vue.js

### ISSUE THREAD

**Issue by sebastianserna** [acuariux/swan-vue#1]
Este issue ha sido trasladado desde el repositorio principal de [Swan](https://github.com/acuariux/swan) para hacer un seguimiento a los componentes de Vue que se van a crear ya que el proyecto principal será solo en HTML y CSS https://github.com/acuariux/swan/issues/41

[Vue.js](http://vuejs.org/) es la librería JavaScript que utilizaremos en el proyecto Swan-Vue. Esta librería es potente, elegante y está teniendo mucha acogida por la comunidad de desarrolladores, por ejemplo ha sido elegida como la librería front-end por defecto del framework Laravel (que permite desarrollar aplicaciones web con el lenguaje PHP).

Los componentes básicos en los que podemos concentrarnos para iniciar son:
- [ ] [Menú lateral (off-canvas)](#45)
- [ ] Menú básico con submenús
- [ ] [Scroll personalizado](#46)
- [ ] [Switch (ON / OFF)](#44)
- [ ] Dropdown (custom select)
- [ ] [Slideshow](#48)
- [ ] [Panel de pestañas](#47)

En el sitio [http://vuejsexamples.com/ ](http://vuejsexamples.com/)se listan ejemplos de componentes creados con Vue.js podemos revisarlos y decidir si utilizamos algunos.
